// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3-nhx9qN9LG4I9h3mA_Yit9JB27RGfZQ',
    appId: '1:185093380460:web:0dedf9c755f2ea05c3bb49',
    messagingSenderId: '185093380460',
    projectId: 'geofinalapp',
    authDomain: 'geofinalapp.firebaseapp.com',
    storageBucket: 'geofinalapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE94W18o8Z9Ky1vNkXZA1W43k0ATgxBfw',
    appId: '1:185093380460:android:c1be38b3f403f754c3bb49',
    messagingSenderId: '185093380460',
    projectId: 'geofinalapp',
    storageBucket: 'geofinalapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH4OhOD-XSdz6z7ycraORAWojFffOsxFY',
    appId: '1:185093380460:ios:6143916993e28582c3bb49',
    messagingSenderId: '185093380460',
    projectId: 'geofinalapp',
    storageBucket: 'geofinalapp.firebasestorage.app',
    iosBundleId: 'com.example.geofinalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH4OhOD-XSdz6z7ycraORAWojFffOsxFY',
    appId: '1:185093380460:ios:6143916993e28582c3bb49',
    messagingSenderId: '185093380460',
    projectId: 'geofinalapp',
    storageBucket: 'geofinalapp.firebasestorage.app',
    iosBundleId: 'com.example.geofinalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3-nhx9qN9LG4I9h3mA_Yit9JB27RGfZQ',
    appId: '1:185093380460:web:1bdee38713f67dc6c3bb49',
    messagingSenderId: '185093380460',
    projectId: 'geofinalapp',
    authDomain: 'geofinalapp.firebaseapp.com',
    storageBucket: 'geofinalapp.firebasestorage.app',
  );
}
